language: node_js
node_js:
  - 14
os:
  - "linux"

dist:
  - xenial

before_install:
  - npm i c8 -g
  - npm i coveralls -g
  - npm --version

install:
  - npm install

cache:
  directories:
    - "$HOME/.npm"

script:
  - ./node_modules/.bin/c8 report --reporter=text-lcov | ./node_modules/.bin/coveralls
  - npm run test

notifications:
  - email: false
