language: node_js
node_js:
  - 14
os:
  - "linux"

dist:
  - xenial

install:
  - npm install
  - npm i c8 -g

cache:
  directories:
    - "$HOME/.npm"

script:
  - c8 report --reporter=text-lcov | coveralls
  - npm run test

notifications:
  - email: false
