language: node_js
node_js:
  - 14
os:
  - "linux"

dist:
  - xenial

install:
  - npm install

cache:
  directories:
    - "$HOME/.npm"

script:
  - npm run coverage
  - npm run test

notifications:
  - email: false
